{% set name = "clans_linux" %}
{% set version = "2.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_tag: {{ version }}
  url: https://github.com/inbalpaz/CLANS/releases/download/{{ version }}/CLANS_{{ version }}.tar.gz
  sha256: a1bc7abc9f5c238a4e9c7253778842df36766ceb9a9e5cdccd5f7499e9d2a3a7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  string: np_mkl_noBlast_noPyQt

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy =1.20.3
    - numba =0.53.1
    - vispy =0.8.1
    - biopython >=1.77
    - pillow =8.3.1

test:
  imports:
    - clans
    - clans.config
    - clans.clans_cmd
    - clans.clans
    - clans.clans.io
    - clans.clans.io.file_formats
    - clans.clans.GUI
    - clans.clans.data
    - clans.clans.graphics
    - clans.clans.layouts
    - clans.clans.similarity_search
    - clans.clans.taxonomy
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/inbalpaz/CLANS
  summary: 'Network clustering and visualization tool'
  description: |
    CLANS 2.0 is a Python-based program for clustering sequences in the 2D or 3D space,
    based on their sequence similarities.
    CLANS visualizes the dynamic clustering process and enables the user to interactively control it
    and explore the cluster map in various ways.
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  doc_url: https://github.com/inbalpaz/CLANS/blob/master/README.md

extra:
  recipe-maintainers:
   - inbalpaz
